services:
  frontend:
    image: node:20
    working_dir: /app
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: dev.backend.Dockerfile
    env_file: .env.dev
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --method=GET --output-document=/dev/null http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 15s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=padel_services
      - POSTGRES_USER=aflori
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aflori -d padel_services"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./resources/sql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
      - ./resources/sql/secrets.sql:/docker-entrypoint-initdb.d/secrets.sql
